version: '3.8'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/mysql:rw  ##persistence data
      - type: bind
        source: ./initdb
        target: /docker-entrypoint_initdb.d/ ## init db setting
        bind:
          propagation: rprivate
    ports:
      - 3306:3306
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: signal
      MYSQL_USER: root
      MYSQL_PASSWORD: test
volumes:
  dbdata: 
